# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: VMWare or EC2 Auto Deploy (CI/CD)

on:
  push:
    branches: [main]
env:
  ENV_SECRET: ${{ secrets.ENV_SECRET }}

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check current working directory
        run: pwd
      - name: Remove old .env file
        run: rm -r -f .env
      - name: Create env2 file
        run: touch .env2
      - name: Copy Secret Key Multiline environment variable to .env2 file
        run: echo $ENV_SECRET >> .env2
